version: "3.8"

valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
    restart: unless-stopped


## docker run -d --name valkey -p 6379:6379 valkey/valkey:latest